# Generated by Django 4.2.5 on 2023-10-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0002_addnewtablefromcmd_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('date', models.DateField(verbose_name='日期')),
                ('time', models.TimeField(verbose_name='时间')),
            ],
        ),
        migrations.DeleteModel(
            name='ReviewappManager',
        ),
    ]
