# Generated by Django 4.2.5 on 2023-10-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0003_manager_delete_reviewappmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'managed': False},
        ),
    ]
