# Generated by Django 4.2.5 on 2023-10-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0005_fltester_alter_manager_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fltester',
            name='name',
        ),
    ]
