# Generated by Django 4.2.5 on 2023-10-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0006_remove_fltester_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fltester',
            old_name='Laser_beam_on_off',
            new_name='Triger_3D',
        ),
    ]
