# Generated by Django 4.2.5 on 2023-10-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0007_rename_laser_beam_on_off_fltester_triger_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='fltester',
            name='GPIO_4',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
